class ShampooRunner{

  public static void main(String[] toWash){
  
    Shampoo ref=new Shampoo();
    ref.brandName="Dove";
    ref.id=1;
    ref.quantity="200ml";
    ref.type="Regular";
    ref.price=200.00;
    ref.mgfDate="21/06/2023";
    ref.expDate="23/07/2025";

    System.out.println("Brand Name: "+ref.brandName);
    System.out.println("Shampoo Id: "+ref.id);  
    System.out.println("Quantity: "+ref.quantity);
    System.out.println("Shampoo Type: "+ref.type);
    System.out.println("Price: "+ref.price);
    System.out.println("MagDate: "+ref.mgfDate);
    System.out.println("ExpDate: "+ref.expDate); 
    System.out.println("-----------------------------------------------------------------");
	Shampoo ref1=new Shampoo();
    ref1.brandName="Himalaya";
    ref1.id=2;
    ref1.quantity="500ml";
    ref1.type="Everey day use";
    ref1.price=420.00;
    ref1.mgfDate="10/02/2024";
    ref1.expDate="23/07/2026";

    System.out.println("Brand Name: "+ref1.brandName);
    System.out.println("Shampoo Id: "+ref1.id);  
    System.out.println("Quantity: "+ref1.quantity);
    System.out.println("Shampoo Type: "+ref1.type);
    System.out.println("Price: "+ref1.price);
    System.out.println("MagDate: "+ref1.mgfDate);
    System.out.println("ExpDate: "+ref1.expDate);
    System.out.println("-----------------------------------------------------------------");
    Shampoo ref2=new Shampoo();
    ref2.brandName="Mamaearth";
    ref2.id=3;
    ref2.quantity="250ml";
    ref2.type="Clarifing Sahmpoo";
    ref2.price=500.00;
    ref2.mgfDate="19/09/2022";
    ref2.expDate="02/11/2025";

    System.out.println("Brand Name: "+ref2.brandName);
    System.out.println("Shampoo Id: "+ref2.id);  
    System.out.println("Quantity: "+ref2.quantity);
    System.out.println("Shampoo Type: "+ref2.type);
    System.out.println("Price: "+ref2.price);
    System.out.println("MagDate: "+ref2.mgfDate);
    System.out.println("ExpDate: "+ref2.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref3=new Shampoo();
    ref3.brandName="Garnier";
    ref3.id=4;
    ref3.quantity="230ml";
    ref3.type="";
    ref3.price=200.00;
    ref3.mgfDate="01/11/2022";
    ref3.expDate="12/01/2024";

    System.out.println("Brand Name: "+ref3.brandName);
    System.out.println("Shampoo Id: "+ref3.id);  
    System.out.println("Quantity: "+ref3.quantity);
    System.out.println("Shampoo Type: "+ref3.type);
    System.out.println("Price: "+ref3.price);
    System.out.println("MagDate: "+ref3.mgfDate);
    System.out.println("ExpDate: "+ref3.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref4=new Shampoo();
    ref4.brandName="Pantene";
    ref4.id=5;
    ref4.quantity="600ml";
    ref4.type="Anti-breakage Shampoo";
    ref4.price=850.00;
    ref4.mgfDate="12/12/2024";
    ref4.expDate="01/06/2025";

    System.out.println("Brand Name: "+ref4.brandName);
    System.out.println("Shampoo Id: "+ref4.id);  
    System.out.println("Quantity: "+ref4.quantity);
    System.out.println("Shampoo Type: "+ref4.type);
    System.out.println("Price: "+ref4.price);
    System.out.println("MagDate: "+ref4.mgfDate);
    System.out.println("ExpDate: "+ref4.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref5=new Shampoo();
    ref5.brandName="Head and Shoulders";
    ref5.id=6;
    ref5.quantity="700ml";
    ref5.type="Purifying Shampoo";
    ref5.price=280.00;
    ref5.mgfDate="06/06/2021";
    ref5.expDate="12/12/2024";

    System.out.println("Brand Name: "+ref5.brandName);
    System.out.println("Shampoo Id: "+ref5.id);  
    System.out.println("Quantity: "+ref5.quantity);
    System.out.println("Shampoo Type: "+ref5.type);
    System.out.println("Price: "+ref5.price);
    System.out.println("MagDate: "+ref5.mgfDate);
    System.out.println("ExpDate: "+ref5.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref6=new Shampoo();
    ref6.brandName="Patanjali";
    ref6.id=7;
    ref6.quantity="600ml";
    ref6.type="Hair growth";
    ref6.price=850.00;
    ref6.mgfDate="11/03/2024";
    ref6.expDate="11/03/2027";

    System.out.println("Brand Name: "+ref6.brandName);
    System.out.println("Shampoo Id: "+ref6.id);  
    System.out.println("Quantity: "+ref6.quantity);
    System.out.println("Shampoo Type: "+ref6.type);
    System.out.println("Price: "+ref6.price);
    System.out.println("MagDate: "+ref6.mgfDate);
    System.out.println("ExpDate: "+ref6.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref7=new Shampoo();
    ref7.brandName="Vatica";
    ref7.id=8;
    ref7.quantity="500ml";
    ref7.type="Moisturizing Shampoo";
    ref7.price=320.00;
    ref7.mgfDate="11/07/2024";
    ref7.expDate="08/04/2028";

    System.out.println("Brand Name: "+ref7.brandName);
    System.out.println("Shampoo Id: "+ref7.id);  
    System.out.println("Quantity: "+ref7.quantity);
    System.out.println("Shampoo Type: "+ref7.type);
    System.out.println("Price: "+ref7.price);
    System.out.println("MagDate: "+ref7.mgfDate);
    System.out.println("ExpDate: "+ref7.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref8=new Shampoo();
    ref8.brandName="Sunsilk";
    ref8.id=9;
    ref8.quantity="500ml";
    ref8.type="";
    ref8.price=400.00;
    ref8.mgfDate="11/01/2024";
    ref8.expDate="23/01/2025";

    System.out.println("Brand Name: "+ref8.brandName);
    System.out.println("Shampoo Id: "+ref8.id);  
    System.out.println("Quantity: "+ref8.quantity);
    System.out.println("Shampoo Type: "+ref8.type);
    System.out.println("Price: "+ref8.price);
    System.out.println("MagDate: "+ref8.mgfDate);
    System.out.println("ExpDate: "+ref8.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref9=new Shampoo();
    ref9.brandName="L'oreal";
    ref9.id=10;
    ref9.quantity="230ml";
    ref9.type="Volumizing Shampoo";
    ref9.price=200.00;
    ref9.mgfDate="01/11/2022";
    ref9.expDate="12/01/2024";

    System.out.println("Brand Name: "+ref9.brandName);
    System.out.println("Shampoo Id: "+ref9.id);  
    System.out.println("Quantity: "+ref9.quantity);
    System.out.println("Shampoo Type: "+ref9.type);
    System.out.println("Price: "+ref9.price);
    System.out.println("MagDate: "+ref9.mgfDate);
    System.out.println("ExpDate: "+ref9.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref10=new Shampoo();
    ref10.brandName="TRESemme";
    ref10.id=11;
    ref10.quantity="50ml";
    ref10.type="Silky Hair";
    ref10.price=800.00;
    ref10.mgfDate="13/04/2023";
    ref10.expDate="12/01/2025";

    System.out.println("Brand Name: "+ref10.brandName);
    System.out.println("Shampoo Id: "+ref10.id);  
    System.out.println("Quantity: "+ref10.quantity);
    System.out.println("Shampoo Type: "+ref10.type);
    System.out.println("Price: "+ref10.price);
    System.out.println("MagDate: "+ref10.mgfDate);
    System.out.println("ExpDate: "+ref10.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref11=new Shampoo();
    ref11.brandName="Lemon Shampoo";
    ref11.id=12;
    ref11.quantity="250ml";
    ref11.type="Dundruf free Shampoo";
    ref11.price=100.00;
    ref11.mgfDate="01/11/2023";
    ref11.expDate="12/01/2026";

    System.out.println("Brand Name: "+ref11.brandName);
    System.out.println("Shampoo Id: "+ref11.id);  
    System.out.println("Quantity: "+ref11.quantity);
    System.out.println("Shampoo Type: "+ref11.type);
    System.out.println("Price: "+ref11.price);
    System.out.println("MagDate: "+ref11.mgfDate);
    System.out.println("ExpDate: "+ref11.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref12=new Shampoo();
    ref12.brandName="SebaMed";
    ref12.id=13;
    ref12.quantity="1L";
    ref12.type="regular for babies";
    ref12.price=1700.00;
    ref12.mgfDate="03/01/2024";
    ref12.expDate="08/01/2026";

    System.out.println("Brand Name: "+ref12.brandName);
    System.out.println("Shampoo Id: "+ref12.id);  
    System.out.println("Quantity: "+ref12.quantity);
    System.out.println("Shampoo Type: "+ref12.type);
    System.out.println("Price: "+ref12.price);
    System.out.println("MagDate: "+ref12.mgfDate);
    System.out.println("ExpDate: "+ref12.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref13=new Shampoo();
    ref13.brandName="Clink Plus";
    ref13.id=14;
    ref13.quantity="2ml";
    ref13.type="Strong Hair";
    ref13.price=2.00;
    ref13.mgfDate="03/11/2023";
    ref13.expDate="21/05/2025";

    System.out.println("Brand Name: "+ref13.brandName);
    System.out.println("Shampoo Id: "+ref13.id);  
    System.out.println("Quantity: "+ref13.quantity);
    System.out.println("Shampoo Type: "+ref13.type);
    System.out.println("Price: "+ref13.price);
    System.out.println("MagDate: "+ref13.mgfDate);
    System.out.println("ExpDate: "+ref13.expDate);	
	System.out.println("-----------------------------------------------------------------");
	Shampoo ref14=new Shampoo();
    ref14.brandName="Nile";
    ref14.id=15;
    ref14.quantity="100ml";
    ref14.type="Damage Repair";
    ref14.price=115.00;
    ref14.mgfDate="06/11/2023";
    ref14.expDate="12/01/2026";

    System.out.println("Brand Name: "+ref14.brandName);
    System.out.println("Shampoo Id: "+ref14.id);  
    System.out.println("Quantity: "+ref14.quantity);
    System.out.println("Shampoo Type: "+ref14.type);
    System.out.println("Price: "+ref14.price);
    System.out.println("MagDate: "+ref14.mgfDate);
    System.out.println("ExpDate: "+ref14.expDate);	
	System.out.println("-----------------------------------------------------------------");
  }
}